# Generated by Django 4.2.2 on 2023-06-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_reply_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="categgories",
            new_name="categories",
        ),
    ]
