# Generated by Django 4.2.2 on 2023-06-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_categgories_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(blank=True, to="main.comment"),
        ),
    ]
