# Generated by Django 4.2.2 on 2023-06-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_post_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="state",
            field=models.CharField(default="zero", max_length=40),
        ),
    ]
